services:

  discovery-server:
    image: husarnet/ros:humble-ros-core
    network_mode: service:husarnet
    ipc: service:husarnet
    depends_on: 
      husarnet: { condition: service_healthy }
    environment:
      - DISCOVERY_SERVER_PORT=11811
    command: fast-discovery-server -x /var/tmp/husarnet-dds/fastdds-ds-server.xml

  chatter:
    build:
      context: .
      args:
        - ROS_DISTRO=${ROS_DISTRO}
    network_mode: service:husarnet
    ipc: service:husarnet
    depends_on: 
      husarnet: { condition: service_healthy }
    environment:
      - RMW_IMPLEMENTATION
      - FASTRTPS_DEFAULT_PROFILES_FILE
      - CYCLONEDDS_URI
      - ROS_DISCOVERY_SERVER
    command: ros2 run demo_nodes_cpp ${CHATTER_ROLE}

  husarnet:
    image: husarnet/husarnet:2.0.13
    ipc: shareable
    volumes:
      - /var/lib/husarnet
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment: 
      - HOSTNAME
      - JOINCODE
      - WAIT_HOSTNAMES
      - HUSARNET_DEBUG=1